version: "3.8"

services:
  frontend:
    image: ghcr.io/yaterie2/solar_frontend:latest
    deploy:
      replicas: 1
      update_config:
        delay: 10s
        failure_action: rollback
        order: start-first
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=proxy"
        - "traefik.http.routers.${FRONTEND_SUBDOMAIN}.rule=Host(`${FRONTEND_SUBDOMAIN}.${DOMAIN}`)"
        - "traefik.http.routers.${FRONTEND_SUBDOMAIN}.entrypoints=https"
        - "traefik.http.routers.${FRONTEND_SUBDOMAIN}.tls=true"
        - "traefik.http.routers.${FRONTEND_SUBDOMAIN}.tls.certresolver=cf"
        - "traefik.http.services.${FRONTEND_SUBDOMAIN}.loadbalancer.server.port=80"
        - "traefik.http.services.${FRONTEND_SUBDOMAIN}.loadbalancer.server.scheme=http"
    networks:
      - proxy

  backend:
    image: ghcr.io/yaterie2/solar_api:latest
    environment:
      - API_PORT=${API_PORT}
      - FRONTEND_URL=https://${FRONTEND_SUBDOMAIN}.${DOMAIN}
      - MONGO_COLLECTION=${MONGO_COLLECTION}
      - MONGO_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@solarapp_mongodb:27017/${MONGO_DB}?authSource=admin
      - MONGO_DB=${MONGO_DB}
    deploy:
      replicas: 1
      update_config:
        delay: 10s
        failure_action: rollback
        order: start-first
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=proxy"
        - "traefik.http.routers.${BACKEND_SUBDOMAIN}.rule=Host(`${BACKEND_SUBDOMAIN}.${DOMAIN}`)"
        - "traefik.http.routers.${BACKEND_SUBDOMAIN}.entrypoints=https"
        - "traefik.http.routers.${BACKEND_SUBDOMAIN}.tls=true"
        - "traefik.http.routers.${BACKEND_SUBDOMAIN}.tls.certresolver=cf"
        - "traefik.http.services.${BACKEND_SUBDOMAIN}.loadbalancer.server.port=${API_PORT}"
        - "traefik.http.services.${BACKEND_SUBDOMAIN}.loadbalancer.server.scheme=http"

    networks:
      - proxy
      - solar

  mongodb:
    image: mongo:7
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    deploy:
      replicas: 1
      update_config:
        delay: 10s
        failure_action: rollback
    ports:
      - 27017:27017
    networks:
      - proxy
      - solar

networks:
  proxy:
    external: true
  starbugs_network:

volumes:
  mongo_data:
